### ISSUE TITLE
Running a build on heroku

### ISSUE THREAD

**Issue by andymac** [normative/normative-react#16]
It would be nice if we could get this to run out of the box on Heroku - Right now its not possible without getting babel running in Heroku or running a build locally, committing the dist/ folder and starting the app from the dist/server.js file directly.

**Comment by tonybennett** [comment]
Odd, it should already be setup, worked on r-beautiful.

**Comment by andymac** [comment]
Hmm, didn't for me but I might have done something silly - I'll try to recreate the issue I had and post the results

**Comment by tonybennett** [comment]
Closing this since it seems to be working ok.
